/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserSchemaJson {
  userId: string;
  name: string;
  email: string;
  address: ResidentialSchemaJson | BusinessSchemaJson;
  [k: string]: unknown;
}
export interface ResidentialSchemaJson {
  type: "residential";
  householdName: string;
  [k: string]: unknown;
}
export interface BusinessSchemaJson {
  type: "business";
  companyName: string;
  [k: string]: unknown;
}
